name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore build/Kyameru.Component.Ftp.sln
    - name: Build
      run: dotnet build build/Kyameru.Component.Ftp.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/UnitTests/Kyameru.Component.Ftp.Tests/Kyameru.Component.Ftp.Tests.csproj --no-restore --verbosity normal
